#!/bin/sh

# Copyright (C) 2022, Sol Boucher
#
# This file is part of OpenVSCode GDrive.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

readonly DISPLAY_MODE="800x600"
readonly X11_PORT="5900"
readonly VNC_PORT="6080"

read access_token
read refresh_token
read expiry
read display
cd

cat <<-tac >.rclone.conf
	[drive]
	type = drive
	scope = drive
	token = {"access_token":"$access_token","token_type":"Bearer","refresh_token":"$refresh_token","expiry":"$expiry"}
tac
rclone mount --daemon --allow-non-empty drive: ~

for dotfile in .*
do
	if [ -f "$dotfile" -a ! -e ~/"$dotfile" -a "$dotfile" != ".rclone.conf" ]
	then
		mv "$dotfile" ~
	fi
done
cd

if which novnc_proxy >/dev/null
then
	mkdir /tmp/.cache
	mkdir -p .cache
	mount -B /tmp/.cache .cache

	Xvnc -SecurityTypes None -localhost -nolisten local ":$display" 2>/dev/null &
	novnc_proxy --vnc ":$((X11_PORT + display))" --listen $((VNC_PORT + display)) 2>/dev/null &
	sleep 2

	export DISPLAY=":$display"
	[ -n "$DISPLAY_MODE" ] && xrandr --output VNC-0 --mode "$DISPLAY_MODE"
fi

exec unshare -U openvscode-server "$@"
