#!/bin/sh

readonly X11_PORT="5900"
readonly VNC_PORT="6080"

read access_token
read refresh_token
read expiry
read display
cd

cat <<-tac >.rclone.conf
	[drive]
	type = drive
	scope = drive
	token = {"access_token":"$access_token","token_type":"Bearer","refresh_token":"$refresh_token","expiry":"$expiry"}
tac
rclone mount --daemon --allow-non-empty drive: ~

for dotfile in .*
do
	if [ -f "$dotfile" -a ! -e ~/"$dotfile" -a "$dotfile" != ".rclone.conf" ]
	then
		mv "$dotfile" ~
	fi
done
cd

if which novnc_proxy >/dev/null
then
	mkdir /tmp/.cache
	mkdir -p .cache
	mount -B /tmp/.cache .cache

	Xvnc -SecurityTypes None -localhost -nolisten local ":$display" 2>/dev/null &
	novnc_proxy --vnc ":$((X11_PORT + display))" --listen $((VNC_PORT + display)) 2>/dev/null &

	export DISPLAY=":$display"
fi

exec unshare -U openvscode-server "$@"
